### ISSUE TITLE
Perform apache incubator source release

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2513]
This issue will track the tasks needed to perform an ASF release

- [x] remove travis publish setup #2523
- [x] maven build #2517
- [x] deal with any RAT license audit concerns
  - [x] add licenses to UI assets and stop skipping license check #2539
  - [x] add license to SQL files #2541
- [x] setup jenkins #2542
- [ ] change quick start links to use apache group ID in very many places
- [ ] update common dependencies to use org.apache.zipkin.zipkin2:zipkin
  - [x] zipkin
    * README.md
    * zipkin-server/README.md
    * zipkin-autoconfigure/collector-kafka08/README.md
    * zipkin-autoconfigure/collector-kafka08/pom.xml
    * zipkin-storage/cassandra-v1/src/main/java/zipkin2/storage/cassandra/v1/CassandraStorage.java
    * zipkin-storage/cassandra/src/main/java/zipkin2/storage/cassandra/CassandraStorage.java
  - [ ] brave
  - [ ] zipkin-reporter

**Comment by codefromthecrypt** [comment]
we have a decision to make about group IDs based on this valid comment from @devinsba https://github.com/apache/incubator-zipkin/pull/2517#discussion_r277020346

Right now, the change moves things into o.a.z.zipkin2 like so
```diff
-  <groupId>io.zipkin.zipkin2</groupId>
+  <groupId>org.apache.zipkin.zipkin2</groupId>
```

This would mean there is no artifact in `org.apache.zipkin`, rather each repo has a subpath underneath. We could choose the main repo to put its assets under `org.apache.zipkin` directly. This would look neater at the moment. there's a future consideration though. When we make an api incompatible change, we'd want to make a `org.apache.zipkin.zipkin3` at that point, so that old and new classes could co-exist. In other words, it might only be temporarily the case that we could use the root directory `org.apache.zipkin`.

If we choose to not use `org.apache.zipkin`, we have choice of `org.apache.zipkin.zipkin2` (to match now) or `org.apache.zipkin.zipkin` (to remove the 2 since there's no ambiguity, yet).

This mainly affects java people, but it also affects download urls for the zipkin server jar.

Thoughts?

**Comment by devinsba** [comment]
Having thought about it a bit more, my updated opinion would be that the library artifacts (those that are reusable, probably not the starters) are `org.apache.zipkin.zipkin2` but everything else is `org.apache.zipkin`. I think that presents the nicest look for those pulling the server jar but also allows all the other reusable components to progress as needed

**Comment by codefromthecrypt** [comment]
maybe o.a.z.server? there are a lot of "junk modules" so i think dumping
all the auto config etc. in o.a.z might not look as nice as we expect.

o.a.z.server is a good idea same thing as you mention because we dont ever
expect collocation of different major versions in same jvm

**Comment by codefromthecrypt** [comment]
actually I am also fine with Brian's suggestion. since we dont support
custom servers anymore anyway I think we can fold almost all auto config
modules into the main server anyway, leaving only the optional ones for
scribe and kafka08

**Comment by codefromthecrypt** [comment]
I'm working on inlining now. https://github.com/apache/incubator-zipkin/pull/2524

**Comment by codefromthecrypt** [comment]
inlining done

**Comment by codefromthecrypt** [comment]
no longer relevant
