### ISSUE TITLE
Release!

### ISSUE THREAD

**Issue by abesto** [openzipkin/zipkin#579]
- [x] Publish an RC via Travis (by creating a tag)
- [x] Get approval for snapshot releases to oss.jfrog.org
- [x] Push snapshot releases via Travis on each successful build on master
- [x] Generate, upload docs to Bintray
- [x] Upload sources to Bintray
- [x] Get the release into jcenter
  - Verify release by building https://github.com/openzipkin/zipkin-mongodb/pull/1
- [x] Publish `SpanStoreSpec` in a jar with `test` classifier
- [x] Sync the release to Maven Central
- [x] Publish a final release (via Travis, by creating a tag)
- [x] Add the version badge to the README! :)
- [x] Migrate [docker-zipkin](https://github.com/openzipkin/docker-zipkin) to published artifacts
- [ ] Pin and release [zipkin-mongodb](https://github.com/openzipkin/zipkin-mongodb/issues/2)
- [ ] Pin and release [zipkin-hbase](https://github.com/openzipkin/zipkin-hbase/issues/2)
## Minor issues
- [x] The Travis run with `gradle release` and `gradle bintrayUpload` duplicate some work, we can probably save some of it
- [ ] Create, use dedicated user for release commits, or even better, a [deploy key](https://developer.github.com/guides/managing-deploy-keys/#deploy-keys)
- [x] All the packages other than `zipkin` need to be deleted from Bintray (we're uploading all artifacts into one package)
- [x] Don't build artifacts we won't upload (for example, `distZip`). See #635 for details on why this is not trivial.
## Tentative release notes
- Cassandra
  - Replaced internally cloned Cassie with the DataStax CQL driver
  - Change keyspace name from "Zipkin" to "zipkin"
  - Automatic schema creation on first start

**Comment by codefromthecrypt** [comment]
@michaelsembwever added your note for release here. thx!

**Comment by codefromthecrypt** [comment]
https://repo1.maven.org/maven2/io/zipkin/zipkin-query-service/1.2.1-rc24/

**Comment by codefromthecrypt** [comment]
note there's still a glitch as automatic publishing doesn't work #644

**Comment by codefromthecrypt** [comment]
this is pretty much done, right?

**Comment by abesto** [comment]
zipkin-mongodb and zipkin-hbase aren't, and i'm guessing there are a couple of other spun-out projects that also need love? maybe those should be tracked in a separate issue though.

**Comment by codefromthecrypt** [comment]
that reminds me...

**Comment by eirslett** [comment]
Well, let's not worry about zipkin-mongodb and zipkin-hbase releases until somebody actually asks for it.
